Akshat Rastogi
E20CSE003

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn import preprocessing
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import minmax_scale
from sklearn.metrics import mean_squared_error
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn import svm
from sklearn.tree import DecisionTreeClassifier 
from sklearn import metrics
from sklearn.preprocessing import MultiLabelBinarizer, StandardScaler
from sklearn.metrics import confusion_matrix, precision_recall_fscore_support
import warnings
warnings.filterwarnings("ignore")

In [ ]:
#Ques.1
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
data = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/agaricus-lepiota.data",na_values="?",names=['class','cap-shape','cap-surface','cap-color','bruises?','odor','gill-attachment','gill-spacing','gill-size','gill-color','stalk-shape','stalk-root','stalk-surface-above-ring','stalk-surface-below-ring','stalk-color-above-ring','stalk-color-below-ring','veil-type','veil-color','ring-number','ring-type','spore-print-color','population','habitat'])
data

     class cap-shape cap-surface  ... spore-print-color population habitat
0        p         x           s  ...                 k          s       u
1        e         x           s  ...                 n          n       g
2        e         b           s  ...                 n          n       m
3        p         x           y  ...                 k          s       u
4        e         x           s  ...                 n          a       g
...    ...       ...         ...  ...               ...        ...     ...
8119     e         k           s  ...                 b          c       l
8120     e         x           s  ...                 b          v       l
8121     e         f           s  ...                 b          c       l
8122     p         k           y  ...                 w          v       l
8123     e         x           s  ...                 o          c       l

[8124 rows x 23 columns]

In [ ]:
#Ques.4
print("Missing values for each column:\n", data.isnull().sum())

Missing values for each column:
 class                          0
cap-shape                      0
cap-surface                    0
cap-color                      0
bruises?                       0
odor                           0
gill-attachment                0
gill-spacing                   0
gill-size                      0
gill-color                     0
stalk-shape                    0
stalk-root                  2480
stalk-surface-above-ring       0
stalk-surface-below-ring       0
stalk-color-above-ring         0
stalk-color-below-ring         0
veil-type                      0
veil-color                     0
ring-number                    0
ring-type                      0
spore-print-color              0
population                     0
habitat                        0
dtype: int64

In [ ]:
print("Total null values",data.isnull().sum().sum())

Total null values 2480

In [ ]:
Handling_null_values=data['stalk-root'].fillna(data['stalk-root'].mode()[0], inplace=False)
print(Handling_null_values)

0       e
1       c
2       c
3       e
4       e
       ..
8119    b
8120    b
8121    b
8122    b
8123    b
Name: stalk-root, Length: 8124, dtype: object

In [ ]:
#Ques.6
from sklearn.preprocessing import LabelEncoder
data_string = data.dtypes==object
data_cols = data.columns[data_string].tolist()
le = LabelEncoder()
data[data_cols] = data[data_cols].apply(lambda col: le.fit_transform(col))
data

      class  cap-shape  cap-surface  ...  spore-print-color  population  habitat
0         1          5            2  ...                  2           3        5
1         0          5            2  ...                  3           2        1
2         0          0            2  ...                  3           2        3
3         1          5            3  ...                  2           3        5
4         0          5            2  ...                  3           0        1
...     ...        ...          ...  ...                ...         ...      ...
8119      0          3            2  ...                  0           1        2
8120      0          5            2  ...                  0           4        2
8121      0          2            2  ...                  0           1        2
8122      1          3            3  ...                  7           4        2
8123      0          5            2  ...                  4           1        2

[8124 rows x 23 columns]

In [ ]:
#Ques.5
data = data.drop(columns=['veil-type'])
data

      class  cap-shape  cap-surface  ...  spore-print-color  population  habitat
0         1          5            2  ...                  2           3        5
1         0          5            2  ...                  3           2        1
2         0          0            2  ...                  3           2        3
3         1          5            3  ...                  2           3        5
4         0          5            2  ...                  3           0        1
...     ...        ...          ...  ...                ...         ...      ...
8119      0          3            2  ...                  0           1        2
8120      0          5            2  ...                  0           4        2
8121      0          2            2  ...                  0           1        2
8122      1          3            3  ...                  7           4        2
8123      0          5            2  ...                  4           1        2

[8124 rows x 22 columns]

In [ ]:
#Ques.7
X = data.loc[:, data.columns != 'class'].values
X

array([[5, 2, 4, ..., 2, 3, 5],
       [5, 2, 9, ..., 3, 2, 1],
       [0, 2, 8, ..., 3, 2, 3],
       ...,
       [2, 2, 4, ..., 0, 1, 2],
       [3, 3, 4, ..., 7, 4, 2],
       [5, 2, 4, ..., 4, 1, 2]])

In [ ]:
Y = data.iloc[:,0].values
Y

array([1, 0, 0, ..., 0, 1, 0])

In [ ]:
#Ques.8 and 9
from sklearn.ensemble import RandomForestClassifier
x_train, x_test, y_train, y_test = train_test_split(X,Y, test_size=0.7, random_state=42)

In [ ]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((2437, 21), (5687, 21), (2437,), (5687,))

In [ ]:
#Ques.10
clf=RandomForestClassifier(n_estimators=2)
clf.fit(x_train,y_train)
y_pred=clf.predict(x_test)
y_pred

array([0, 1, 1, ..., 0, 1, 1])

In [ ]:
#Ques.11
test_ConfMat_sklearn = confusion_matrix(y_test,y_pred)
print(f"Confusion Matrix on testing set: \n{test_ConfMat_sklearn}")

Confusion Matrix on testing set:
[[2905    0]
 [   0 2782]]

In [ ]:
#Ques.12
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 1.0

In [ ]:
#Ques.13
acc = []
rf = RandomForestClassifier(bootstrap=True, criterion='gini',
 max_depth=2, max_features='auto', max_leaf_nodes=2, min_samples_leaf=1,
 min_samples_split=2, min_weight_fraction_leaf=0.0,
 n_estimators=10, n_jobs=1, random_state=10)
rf.fit(x_train, y_train)
y_pred = rf.predict(x_test)
y_predict_train = rf.predict(x_train)
print("Training Data Set: ",metrics.accuracy_score(y_train,y_predict_train)*100)
acc.append(metrics.accuracy_score(y_test,y_pred))

Training Data Set:  94.00902749281904